// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"code-gen/internal/conf"
	"code-gen/internal/controller"
	"code-gen/internal/dao"
	"code-gen/internal/service"
)

// Injectors from wire.go:

// 注入http服务
func WireApp() *conf.HttpServer {
	logger := conf.NewZapConfig()
	engine := conf.NewGin(logger)
	db := conf.NewGormConfig(logger)
	fileDao := &dao.FileDao{
		Logger: logger,
		Db:     db,
	}
	outDir := &dao.OutDir{
		Db:     db,
		Logger: logger,
	}
	mappingPathDao := &dao.MappingPathDao{
		Db:     db,
		Logger: logger,
	}
	fileService := service.FileService{
		Logger:     logger,
		Dao:        fileDao,
		OutDirDao:  outDir,
		MappingDao: mappingPathDao,
	}
	fileController := controller.NewFileController(engine, fileService, logger)
	groupDao := &dao.GroupDao{
		Logger: logger,
		Db:     db,
	}
	ormDao := &dao.OrmDao{
		Logger: logger,
		Db:     db,
	}
	fileAndGroupDao := &dao.FileAndGroupDao{
		Logger: logger,
		Db:     db,
	}
	groupSvc := service.GroupSvc{
		Logger:          logger,
		Dao:             groupDao,
		FileDao:         fileDao,
		OutDirDao:       outDir,
		MappingDao:      mappingPathDao,
		OrmDao:          ormDao,
		FileAndGroupDao: fileAndGroupDao,
	}
	groupController := controller.NewGroupController(engine, groupSvc, logger)
	ormSvc := service.OrmSvc{
		Logger: logger,
		Dao:    ormDao,
	}
	ormController := controller.NewOrmController(engine, ormSvc, logger)
	mappingSvc := service.MappingSvc{
		Logger:    logger,
		Dao:       mappingPathDao,
		FileDao:   fileDao,
		OutDirDao: outDir,
	}
	mappingController := controller.NewMappingController(engine, mappingSvc, logger)
	fileGenDao := &dao.FileGenDao{
		Db:     db,
		Logger: logger,
	}
	fileGenSvc := service.FileGenSvc{
		Logger:          logger,
		Dao:             fileGenDao,
		OrmDao:          ormDao,
		GroupDao:        groupDao,
		FileDao:         fileDao,
		FileAndGroupDao: fileAndGroupDao,
		MappingDao:      mappingPathDao,
	}
	fileGenController := controller.NewFileGenController(engine, fileGenSvc, logger)
	httpServer := &conf.HttpServer{
		Logger:         logger,
		Engine:         engine,
		FileControl:    fileController,
		GroupControl:   groupController,
		OrmControl:     ormController,
		MappingControl: mappingController,
		FileGenControl: fileGenController,
	}
	return httpServer
}
