// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"code-gen/configs"
	"code-gen/internal/conf"
	"code-gen/internal/controller"
	"code-gen/internal/dao"
	"code-gen/internal/service"
)

// Injectors from wire.go:

// 注入http服务
func WireApp(allConfig *configs.AllConfig) *conf.HttpServer {
	logger := conf.NewZapConfig(allConfig)
	engine := conf.NewGin(logger)
	db := conf.NewGormConfig(allConfig, logger)
	groupDao := &dao.GroupDao{
		Logger: logger,
		Db:     db,
	}
	fileDao := &dao.FileDao{
		Logger: logger,
		Db:     db,
	}
	mappingPathDao := &dao.MappingPathDao{
		Db:     db,
		Logger: logger,
	}
	ormDao := &dao.OrmDao{
		Logger: logger,
		Db:     db,
	}
	fileGenDao := &dao.FileGenDao{
		Db:     db,
		Logger: logger,
	}
	groupSvc := service.GroupSvc{
		Logger:     logger,
		Dao:        groupDao,
		FileDao:    fileDao,
		MappingDao: mappingPathDao,
		OrmDao:     ormDao,
		FileGenDao: fileGenDao,
	}
	groupController := controller.NewGroupController(engine, groupSvc, logger)
	ormSvc := service.OrmSvc{
		Logger:     logger,
		Dao:        ormDao,
		FileGenDao: fileGenDao,
	}
	ormController := controller.NewOrmController(engine, ormSvc, logger)
	mappingSvc := service.MappingSvc{
		Logger:  logger,
		Dao:     mappingPathDao,
		FileDao: fileDao,
	}
	mappingController := controller.NewMappingController(engine, mappingSvc, logger)
	fileGenSvc := service.FileGenSvc{
		Logger:     logger,
		Dao:        fileGenDao,
		OrmDao:     ormDao,
		GroupDao:   groupDao,
		FileDao:    fileDao,
		MappingDao: mappingPathDao,
	}
	fileGenController := controller.NewFileGenController(engine, fileGenSvc, logger)
	staticController := controller.NewStaticController(engine, logger)
	httpServer := &conf.HttpServer{
		Logger:           logger,
		Engine:           engine,
		AllConfig:        allConfig,
		GroupControl:     groupController,
		OrmControl:       ormController,
		MappingControl:   mappingController,
		FileGenControl:   fileGenController,
		StaticController: staticController,
	}
	return httpServer
}
